#!/usr/bin/env python3
"""
make_paper_assets.py — paper icin LaTeX tablolar + PNG figurler.
TEK girdi: mevcut `analysis/*.tsv` (yeniden model kosusu YOK).

Figurler (kullanici spesifikasyonu):
  1) difficulty_stackbar.png  "kac model dogru cevapladi" — tek yatay %100
                              stacked bar; renk = dogru cevaplayan model sayisi
                              (koyu = zor), segment ici adetler.
  2) prompt_effect.png        Iki YAN YANA panel (Gemini-3.6 | 2.5-Lite), her
                              panelin KENDI y-olcegi (zoom) -> TR->EN farki
                              gorunur. Bar rengi = PROMPT DILI (TR mavi, EN
                              turuncu; iki panelde ayni), barlar bitisik; eksen
                              kirigi isareti ile durustluk korunur.
  3) category_accuracy.png    Grouped bar: kategoriler altta (kolay->zor),
                              her kategoride 4 bar, renk = model (legend ustte).

Stil: STIX serif (LaTeX ile ayni doku), Paul Tol muted palet (CVD-safe),
figur-ici baslik yok, ACL kolon olculeri, 300 dpi.

Kullanim: /opt/Anaconda-2021.05/bin/python3 scripts/make_paper_assets.py
"""
from __future__ import annotations

import csv
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import numpy as np

REPO = Path(__file__).resolve().parent.parent
ANALYSIS = REPO / "analysis"
TABLES = REPO / "paper" / "tables"
FIGURES = REPO / "paper" / "figures"

MAIN_TR = [
    "Qwen3.6-35B-A3B",
    "deepseek-v4-flash",
    "gemini-3.6-flash-tr",
    "gemini-2.5-flash-lite-tr",
]
CORRECT_COL = {m: f"{m} correct" for m in MAIN_TR}

DISPLAY = {
    "Qwen3.6-35B-A3B": "Qwen3.6-35B-A3B",
    "deepseek-v4-flash": "DeepSeek-V4-Flash",
    "gemini-3.6-flash-tr": "Gemini-3.6-Flash",
    "gemini-3.6-flash-en": "Gemini-3.6-Flash",
    "gemini-2.5-flash-lite-tr": "Gemini-2.5-Flash-Lite",
    "gemini-2.5-flash-lite-en": "Gemini-2.5-Flash-Lite",
}
CAT_SHORT = {
    "Cuisine": "Cuisine",
    "Literature": "Literature",
    "Sport": "Sport",
    "Politics": "Politics",
    "History": "History",
    "Music": "Music",
    "Media, TV, film, Entertainment": "Media/TV",
    "Traditions & Folk Culture": "Traditions",
    "Places & Landmarks": "Landmarks",
}

# Paul Tol muted (CVD-safe); iki Gemini ayni aile -> koyu/acik mavi
MODEL_COLOR = {
    "gemini-3.6-flash-tr": "#332288",
    "gemini-2.5-flash-lite-tr": "#88CCEE",
    "deepseek-v4-flash": "#CC6677",
    "Qwen3.6-35B-A3B": "#117733",
}
# n_correct 0..4 (indeks=n): koyu = zor; komsu adimlar net ayrisacak sekilde
DIFFICULTY_RAMP = ["#08306B", "#2A6FB0", "#5B9BD1", "#A3C9E5", "#DCE9F6"]
# prompt dili (iki panelde ayni): TR mavi, EN turuncu (Okabe-Ito, CVD-safe)
LANG_COLOR = {"TR": "#0072B2", "EN": "#E69F00"}
INK = "#000000"
MUTED = "#555555"
GRID = "#D9D9D9"


def read_tsv(path):
    with path.open(encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def latex_escape(s: str) -> str:
    return s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")


# =============================================================================
# 1) n_correct kolonu -> analysis/model_correct.tsv
# =============================================================================
def add_n_correct():
    path = ANALYSIS / "model_correct.tsv"
    rows = read_tsv(path)
    fields = list(rows[0].keys())
    if "n_correct" in fields:
        fields.remove("n_correct")
    fields.append("n_correct")

    dist = {k: 0 for k in range(len(MAIN_TR) + 1)}
    for r in rows:
        n = sum(1 for m in MAIN_TR if (r.get(CORRECT_COL[m]) or "").strip() == "True")
        r["n_correct"] = str(n)
        dist[n] += 1

    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, delimiter="\t")
        w.writeheader()
        w.writerows(rows)

    total = sum(dist.values())
    print(f"n_correct eklendi ({total} satir): " +
          ", ".join(f"n={k}:{v}" for k, v in sorted(dist.items())))
    return dist, total


# =============================================================================
# 2) LaTeX tablolar
# =============================================================================
def write_main_results_table():
    rows = read_tsv(ANALYSIS / "model_accuracy.tsv")
    lines = [
        r"% Auto-generated by scripts/make_paper_assets.py — do not edit by hand.",
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Overall accuracy on the Turkish culture QA benchmark "
        r"(126 questions, single generation, soft-contains metric). "
        r"\textsc{Prompt} is the prompt language.}",
        r"  \label{tab:main-results}",
        r"  \begin{tabular}{llrr}",
        r"    \toprule",
        r"    Model & Prompt & Correct & Acc.\ (\%) \\",
        r"    \midrule",
    ]
    for r in rows:
        m = r["Model"]
        prompt = "EN" if m.endswith("-en") else "TR"
        lines.append(f"    {latex_escape(DISPLAY.get(m, m))} & {prompt} & "
                     f"{r['Correct']} & {r['Accuracy(%)']} \\\\")
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    (TABLES / "main_results.tex").write_text("\n".join(lines), encoding="utf-8")
    print("yazildi -> paper/tables/main_results.tex")


def write_prompt_ablation_table(acc):
    families = [
        ("Gemini-3.6-Flash", "gemini-3.6-flash-tr", "gemini-3.6-flash-en"),
        ("Gemini-2.5-Flash-Lite", "gemini-2.5-flash-lite-tr", "gemini-2.5-flash-lite-en"),
    ]
    lines = [
        r"% Auto-generated by scripts/make_paper_assets.py — do not edit by hand.",
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Effect of prompt language on the two Gemini models. "
        r"$\Delta$ is EN$-$TR (percentage points). For Gemini-3.6-Flash the gap "
        r"stems entirely from the \emph{Places \& Landmarks} category.}",
        r"  \label{tab:prompt-ablation}",
        r"  \begin{tabular}{lrrr}",
        r"    \toprule",
        r"    Model & TR (\%) & EN (\%) & $\Delta$ \\",
        r"    \midrule",
    ]
    for disp, tr, en in families:
        lines.append(f"    {disp} & {acc[tr]:.1f} & {acc[en]:.1f} & "
                     f"{acc[en] - acc[tr]:+.1f} \\\\")
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    (TABLES / "prompt_ablation.tex").write_text("\n".join(lines), encoding="utf-8")
    print("yazildi -> paper/tables/prompt_ablation.tex")


# =============================================================================
# 3) Figurler
# =============================================================================
def setup_style():
    plt.rcParams.update({
        "figure.dpi": 150,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
        "font.size": 9,
        "font.family": "serif",
        "font.serif": ["STIXGeneral", "STIX", "Times New Roman", "DejaVu Serif"],
        "mathtext.fontset": "stix",
        "axes.edgecolor": INK,
        "axes.linewidth": 0.6,
        "axes.labelsize": 9,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "xtick.major.size": 2.5,
        "ytick.major.size": 2.5,
        "xtick.major.width": 0.6,
        "ytick.major.width": 0.6,
        "legend.fontsize": 7.5,
        "legend.frameon": False,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.axisbelow": True,
        "grid.color": GRID,
        "grid.linewidth": 0.4,
    })


def _difficulty_legend_handles(dist):
    return [Patch(facecolor=DIFFICULTY_RAMP[k], edgecolor="#CCCCCC",
                  linewidth=0.4, label=f"{k}  (n={dist[k]})")
            for k in sorted(dist, reverse=True)]


def fig_difficulty_stackbar(dist, total):
    """Soru-zorluk dagilimi: tek yatay %100 stacked bar."""
    fig, ax = plt.subplots(figsize=(3.6, 1.0))
    left = 0.0
    for k in sorted(dist, reverse=True):  # 4 -> 0
        v = dist[k]
        ax.barh(0, v, left=left, height=0.5, color=DIFFICULTY_RAMP[k],
                edgecolor="white", linewidth=1.0, zorder=3)
        cx = left + v / 2
        if v >= 10:
            ax.text(cx, 0, str(v), ha="center", va="center", fontsize=7.5,
                    color="white" if k <= 1 else "#1A1A1A")
        else:
            ax.plot([cx, cx], [0.27, 0.38], color="#888888", linewidth=0.5)
            ax.text(cx, 0.42, str(v), ha="center", va="bottom",
                    fontsize=7, color=MUTED)
        left += v

    ax.set_xlim(0, total)
    ax.set_ylim(-0.55, 0.75)
    ax.set_yticks([])
    ax.set_xticks([0, total * 0.25, total * 0.5, total * 0.75, total])
    ax.set_xticklabels(["0%", "25%", "50%", "75%", "100%"])
    ax.set_xlabel("Share of questions")
    ax.spines["left"].set_visible(False)
    ax.legend(handles=_difficulty_legend_handles(dist),
              title="Models correct", title_fontsize=7.5, ncol=5,
              loc="upper center", bbox_to_anchor=(0.5, -0.52),
              handlelength=1.0, handleheight=1.0, columnspacing=0.9,
              handletextpad=0.4)

    fig.savefig(FIGURES / "difficulty_stackbar.png")
    plt.close(fig)
    print("yazildi -> paper/figures/difficulty_stackbar.png")


def fig_prompt_effect(acc):
    """Iki yan yana panel, her panel KENDI (zoom) y-olcegi; bar rengi =
    PROMPT DILI (iki panelde ayni), barlar bitisik; eksen-kirigi isaretli."""
    panels = [
        ("Gemini-3.6-Flash", "gemini-3.6-flash", (92, 98), [92, 94, 96, 98]),
        ("Gemini-2.5-Flash-Lite", "gemini-2.5-flash-lite", (55, 70), [55, 60, 65, 70]),
    ]
    W = 0.5  # bar genisligi; x=0 ve x=W -> bitisik

    fig, axes = plt.subplots(1, 2, figsize=(3.3, 2.0))
    fig.subplots_adjust(wspace=0.55)
    for ax, (disp, key, ylim, yticks) in zip(axes, panels):
        tr_a, en_a = acc[f"{key}-tr"], acc[f"{key}-en"]
        ax.yaxis.grid(True)
        ax.bar(0, tr_a, width=W, facecolor=LANG_COLOR["TR"],
               edgecolor="white", linewidth=0.6, zorder=3)
        ax.bar(W, en_a, width=W, facecolor=LANG_COLOR["EN"],
               edgecolor="white", linewidth=0.6, zorder=3)
        for x, v in ((0, tr_a), (W, en_a)):
            ax.text(x, v + (ylim[1] - ylim[0]) * 0.015, f"{v:.1f}",
                    ha="center", va="bottom", fontsize=7.5, color=INK)
        ax.text(0.5, 1.0, f"$\\Delta$ = {en_a - tr_a:+.1f}",
                transform=ax.transAxes, ha="center", va="bottom",
                fontsize=7.5, color=MUTED)
        ax.set_title(disp, fontsize=8, pad=13)
        ax.set_xticks([])
        ax.set_xlim(-0.75, W + 0.75)
        ax.set_ylim(*ylim)
        ax.set_yticks(yticks)
        # kesik-eksen isareti (y ekseni 0'dan baslamiyor)
        d = 0.015
        ax.plot((-d * 2.2, d * 2.2), (-d, d), transform=ax.transAxes,
                color=INK, linewidth=0.7, clip_on=False)
    axes[0].set_ylabel("Accuracy (%)")

    handles = [Patch(facecolor=LANG_COLOR["TR"], label="Turkish prompt"),
               Patch(facecolor=LANG_COLOR["EN"], label="English prompt")]
    fig.legend(handles=handles, ncol=2, loc="lower center",
               bbox_to_anchor=(0.5, 1.03), handlelength=1.0,
               handleheight=1.0, handletextpad=0.5, columnspacing=1.2)

    fig.savefig(FIGURES / "prompt_effect.png")
    plt.close(fig)
    print("yazildi -> paper/figures/prompt_effect.png")


def fig_category_accuracy():
    """Grouped bar: kategoriler altta (kolay->zor), her kategoride 4 bar,
    renk = model, legend ustte."""
    mat = {r["Model"]: r for r in read_tsv(ANALYSIS / "model_x_category_accuracy.tsv")}
    counts = {r["Category"]: r["Questions"]
              for r in read_tsv(ANALYSIS / "category_accuracy.tsv")}
    cats = sorted(counts, key=lambda c: -np.mean([float(mat[m][c]) for m in MAIN_TR]))
    macc = {r["Model"]: float(r["Accuracy(%)"])
            for r in read_tsv(ANALYSIS / "model_accuracy.tsv")}
    models = sorted(MAIN_TR, key=lambda m: -macc[m])

    x = np.arange(len(cats))
    n = len(models)
    w = 0.19

    fig, ax = plt.subplots(figsize=(6.3, 2.2))
    ax.yaxis.grid(True)
    for i, m in enumerate(models):
        vals = [float(mat[m][c]) for c in cats]
        ax.bar(x + (i - (n - 1) / 2) * w, vals, w, label=DISPLAY[m],
               color=MODEL_COLOR[m], edgecolor="white", linewidth=0.4, zorder=3)

    ax.set_xticks(x)
    ax.set_xticklabels([f"{CAT_SHORT[c]}\n(n={counts[c]})" for c in cats])
    ax.set_ylabel("Accuracy (%)")
    ax.set_ylim(0, 100)
    ax.set_yticks([0, 25, 50, 75, 100])
    ax.set_xlim(-0.55, len(cats) - 0.45)
    ax.tick_params(axis="x", length=0)
    ax.legend(ncol=4, loc="lower center", bbox_to_anchor=(0.5, 1.02),
              handlelength=1.0, handleheight=1.0, handletextpad=0.5,
              columnspacing=1.3)

    fig.savefig(FIGURES / "category_accuracy.png")
    plt.close(fig)
    print("yazildi -> paper/figures/category_accuracy.png")


# =============================================================================
def main():
    TABLES.mkdir(parents=True, exist_ok=True)
    FIGURES.mkdir(parents=True, exist_ok=True)

    acc = {r["Model"]: float(r["Accuracy(%)"])
           for r in read_tsv(ANALYSIS / "model_accuracy.tsv")}

    dist, total = add_n_correct()
    write_main_results_table()
    write_prompt_ablation_table(acc)

    setup_style()
    fig_difficulty_stackbar(dist, total)
    fig_prompt_effect(acc)
    fig_category_accuracy()

    print("\nTamamlandi. paper/tables/*.tex + paper/figures/*.png")


if __name__ == "__main__":
    main()
